---
fullname: Coinductive Traces
shortname: coind-traces
organization: palmskog
community: false
actions: true
dune: true

synopsis: Possibly-infinite traces in Coq

description: |-
  Development in Coq of general possibly-infinite traces and
  properties of such traces.

authors:
- name: Karl Palmskog
  initial: true

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.10 or later
  opam: '{(>= "8.10" & < "8.13~") | (= "dev")}'

tested_coq_opam_versions:
- version: dev
- version: '8.12'
- version: '8.11'
- version: '8.10'

namespace: CoindTraces

build: |-
 ## Building instructions

 ``` shell
 git clone https://github.com/palmskog/coind-traces
 cd coind-traces
 make   # or make -j <number-of-cores-on-your-machine>
 ```

documentation: |-
  ## Documentation

  Inspired by the [Coinductive Trace-Based Semantics for While](https://github.com/palmskog/coind-sem-while).
---
