---
fullname: Coinductive Traces
shortname: coind-traces
organization: palmskog
community: false
action: true
dune: true

synopsis: Possibly-infinite traces in Coq

description: |-
  Development in Coq of possibly-infinite traces and properties
  of such traces via coinduction and corecursion, useful
  for capturing labeled transition systems.

authors:
- name: Keiko Nakata
- name: Tarmo Uustalu
- name: Karl Palmskog

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.10 or later
  opam: '{(>= "8.10" & < "8.13~") | (= "dev")}'

tested_coq_opam_versions:
- version: dev
- version: '8.12'
- version: '8.11'
- version: '8.10'

namespace: CoindTraces

build: |-
 ## Building instructions

 ``` shell
 git clone https://github.com/palmskog/coind-traces
 cd coind-traces
 make   # or make -j <number-of-cores-on-your-machine>
 ```

documentation: |-
  ## Files

  - `Traces.v`: definition and decomposition of possibly-infinite traces
  - `TraceProperties.v`: core trace properties such as finiteness and infiniteness
  - `TraceClassicalProperties.v`: trace properties that require classical logic

  Many definitions and properties are adapted from the
  [Coinductive Trace-Based Semantics for While][coind-sem-url]
  by Nakata and Uustalu.

  [coind-sem-url]: https://github.com/palmskog/coind-sem-while
---
